{
 "title": "Client Info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "orderbook", "label": "Orderbook", "query": { "query": "label_values(instrument)" } }
  ]
 },
 "panels": [
  {
   "title": "Global Order Queue Lag",
   "type": "timeseries",
   "description": "Number of orders sitting in the global channel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "orderbook_queue_size{instrument=\"$orderbook\", queue=\"global\"}",
     "legendFormat": "Lagging orders"
    }
   ]
  },
  {
   "title": "Combined Orders in Client Channels",
   "type": "timeseries",
   "description": "Number of orders sitting in all client channels waiting to be sent to the global queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(orderbook_queue_size{instrument=\"$orderbook\", queue=\"client\"})",
     "legendFormat": "Lagging orders"
    }
   ]
  },
  {
   "title": "Client Order Queue Lag",
   "type": "timeseries",
   "description": "Number of orders sitting in the client channel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (client) (orderbook_queue_size{instrument=\"$orderbook\", queue=\"client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "orderbook_clients_connected{instrument=\"$orderbook\"}",
     "legendFormat": "connections"
    }
   ]
  }
 ]
}