{
 "title": "orderbook",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "orderbook", "label": "Orderbook", "query": { "query": "label_values(instrument)" } }
  ]
 },
 "panels": [
  {
   "title": "Buy Side",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orderbook_level_orders{instrument=\"$orderbook\", side=\"Buy\"}) ",
     "legendFormat": "Total Orders"
    },
    {
     "expr": "count(orderbook_level_orders{instrument=\"$orderbook\", side=\"Buy\"} > 0)",
     "legendFormat": "Price Levels"
    },
    {
     "expr": "sum(orderbook_level_quantity{instrument=\"$orderbook\", side=\"Buy\"}) ",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Sell Side",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orderbook_level_orders{instrument=\"$orderbook\", side=\"Sell\"}) ",
     "legendFormat": "Total Orders"
    },
    {
     "expr": "count(orderbook_level_orders{instrument=\"$orderbook\", side=\"Sell\"} > 0)",
     "legendFormat": "Price Levels"
    },
    {
     "expr": "sum(orderbook_level_quantity{instrument=\"$orderbook\", side=\"Sell\"}) ",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Price Level: Buy Orders",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (price) (\n  orderbook_level_orders{\n    instrument=\"$orderbook\",\n    side=\"Buy\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Level: Buy Quantity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (price) (\n  orderbook_level_quantity{\n    instrument=\"$orderbook\",\n    side=\"Buy\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Level: Sell Orders",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (price) (\n  orderbook_level_orders{\n    instrument=\"$orderbook\",\n    side=\"Sell\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Level: Sell Quantity",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (price) (\n  orderbook_level_quantity{\n    instrument=\"$orderbook\",\n    side=\"Sell\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique Price Levels",
   "type": "timeseries",
   "description": "Number of price levels in the orderbook",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(orderbook_level_orders{instrument=\"$orderbook\", side=\"Buy\"} > 0)",
     "legendFormat": "Buy"
    },
    {
     "expr": "count(orderbook_level_orders{instrument=\"$orderbook\", side=\"Sell\"} > 0)",
     "legendFormat": "Sell"
    }
   ]
  },
  {
   "title": "Order Size",
   "type": "timeseries",
   "description": "Total order size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(orderbook_level_quantity{instrument=\"$orderbook\", side=\"Buy\"}) ",
     "legendFormat": "Buy"
    },
    {
     "expr": "sum(orderbook_level_quantity{instrument=\"$orderbook\", side=\"Sell\"}) ",
     "legendFormat": "Sell"
    }
   ]
  },
  {
   "title": "Best & Worst Order Prices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "orderbook_price_best{instrument=\"$orderbook\", side=\"Buy\"}",
     "legendFormat": "Best Buy"
    },
    {
     "expr": "orderbook_price_best{instrument=\"$orderbook\", side=\"Sell\"}",
     "legendFormat": "Best Sell"
    },
    {
     "expr": "orderbook_price_worst{instrument=\"$orderbook\", side=\"Buy\"}",
     "legendFormat": "Worst Buy"
    },
    {
     "expr": "orderbook_price_worst{instrument=\"$orderbook\", side=\"Sell\"}",
     "legendFormat": "Worst Sell"
    }
   ]
  },
  {
   "title": "Trades/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(orderbook_trades_total{instrument=\"$orderbook\"}[1m]) * 60",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Price Spread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "orderbook_price_best{instrument=\"$orderbook\", side=\"Sell\"}\n- ignoring(side)\norderbook_price_best{instrument=\"$orderbook\", side=\"Buy\"}",
     "legendFormat": "Best"
    },
    {
     "expr": "orderbook_price_worst{instrument=\"$orderbook\", side=\"Sell\"}\n- ignoring(side)\norderbook_price_worst{instrument=\"$orderbook\", side=\"Buy\"}",
     "legendFormat": "Worst"
    }
   ]
  },
  {
   "title": "Size/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(orderbook_trade_size_total{instrument=\"$orderbook\"}[1m]) * 60",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}