{
 "title": "Submitted Orders",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Submitted: Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(client) (client_orders_submitted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted: Side",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(side) (client_orders_submitted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted: Instrument",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instrument) (client_orders_submitted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted: Client + Side",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(client, side) (client_orders_submitted_total)",
     "legendFormat": "{{side}}: {{client}}"
    }
   ]
  },
  {
   "title": "Submitted: Instrument + Side",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by(side, instrument) (client_orders_submitted_total)",
     "legendFormat": "{{side}}: {{instrument}}"
    }
   ]
  },
  {
   "title": "Submitted: Instrument + Client",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum by(instrument, client) (client_orders_submitted_total)",
     "legendFormat": "{{instrument}}: {{client}}"
    }
   ]
  }
 ]
}