{
 "title": "Trade Count",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Trades: Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(client) (client_trades_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trades: Instrument",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instrument) (client_trades_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trades: Instrument + Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(instrument, client) (client_trades_total)",
     "legendFormat": "{{instrument}}: {{client}}"
    }
   ]
  },
  {
   "title": "Trades: Side + Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(client, side) (client_trades_total)",
     "legendFormat": "{{side}}: {{client}}"
    }
   ]
  }
 ]
}