{
 "title": "Trader Decisions & Responses",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(response) (client_orderbook_responses_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(action) (client_trader_actions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response: Trade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(client) (client_orderbook_responses_total{response=\"trade\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Action: Place Order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(client) (client_trader_actions_total{action=\"place\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response: Order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(client) (client_orderbook_responses_total{response=\"order_accepted\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Action: Cancel Order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(client) (client_trader_actions_total{action=\"cancel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response: Cancelled Order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(client) (client_orderbook_responses_total{response=\"cancelled\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Action: Skip Order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(client) (client_trader_actions_total{action=\"skip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response: Cancel Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(client) (client_orderbook_responses_total{response=\"cancel_rejected\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}