apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://telemetry-tempo:3200
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
        filterByTraceID: true
        filterBySpanID: false
