# Shared configuration for services
x-common-env-telemetry: &common-env-telemetry
  OTEL_EXPORTER_OTLP_ENDPOINT: http://telemetry-alloy:4318
  OTEL_METRIC_EXPORT_INTERVAL: "1000"
  PYROSCOPE_URL: http://telemetry-alloy:9999

services:
  generator:
    image: orderbook-trading-generator:latest
    environment:
      RUST_LOG: info
      INSTRUMENT: "ETH-USD"
      START_PRICE: 3100.0
      UPPER_LIMIT: 3800.0
      LOWER_LIMIT: 1900.0
      MARKET_FEED_URL: http://market-feed:8000
      <<: *common-env-telemetry
    depends_on:
      telemetry-alloy:
        condition: service_started
      market-feed:
        condition: service_started
    restart: unless-stopped

  market-feed:
    image: orderbook-trading-market-feed:latest
    environment:
      RUST_LOG: info
      SOCKET: 0.0.0.0:8000
      WS: 0.0.0.0:8001
      <<: *common-env-telemetry
    depends_on:
      telemetry-alloy:
        condition: service_started
    restart: unless-stopped

  client:
    image: orderbook-trading-client:latest
    environment:
      RUST_LOG: info
      MARKET_FEED_URL: ws://market-feed:8001
      ORDERBOOK_URL: ws://orderbook:8002
      <<: *common-env-telemetry
    depends_on:
      telemetry-alloy:
        condition: service_started
      market-feed:
        condition: service_started
      orderbook:
        condition: service_started
    restart: unless-stopped

  orderbook:
    image: orderbook-trading-orderbook:latest
    environment:
      RUST_LOG: info
      INSTRUMENT: "ETH-USD"
      WS: 0.0.0.0:8002
      <<: *common-env-telemetry
    depends_on:
      telemetry-alloy:
        condition: service_started
    restart: unless-stopped

  telemetry-grafana:
    image: grafana/grafana:12.2
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
      GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES: "false"
      GF_ANALYTICS_FEEDBACK_LINKS_ENABLED: "false"
      GF_PLUGINS_PUBLIC_KEY_RETRIEVAL_DISABLED: "true"
      GF_PLUGINS_PREINSTALL_DISABLED: "true"
      GF_NEWS_NEWS_FEED_ENABLED: "false"
    volumes:
      - ../telemetry/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data-volume:/var/lib/grafana
    depends_on:
      - telemetry-loki
      - telemetry-pyroscope
      - telemetry-prometheus
      - telemetry-tempo
    restart: unless-stopped

  telemetry-prometheus:
    image: prom/prometheus:v3.5.4
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    volumes:
      - ../telemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-volume:/prometheus
    restart: unless-stopped

  telemetry-loki:
    image: grafana/loki:3.7
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ../telemetry/loki/loki.yaml:/etc/loki/loki.yaml
      - loki-data-volume:/loki
    restart: unless-stopped

  telemetry-pyroscope:
    image: grafana/pyroscope:2.0.4
    ports:
      - "4040:4040"
    command: -config.file=/etc/pyroscope/pyroscope.yaml
    volumes:
      - ../telemetry/pyroscope/pyroscope.yaml:/etc/pyroscope/pyroscope.yaml
      - pyroscope-data-volume:/data
    restart: unless-stopped

  telemetry-tempo:
    image: grafana/tempo:3.0.2
    ports:
      - "3200:3200"
    command: -config.file=/etc/tempo/tempo.yaml
    volumes:
      - ../telemetry/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo-data-volume:/var/tempo
    restart: unless-stopped

  telemetry-alloy:
    image: grafana/alloy:v1.17.0
    volumes:
      - ../telemetry/grafana/alloy:/etc/alloy
      - alloy-data-volume:/var/lib/alloy/data
    command: run --disable-reporting /etc/alloy/config.alloy
    depends_on:
      - telemetry-loki
      - telemetry-tempo
      - telemetry-pyroscope
      - telemetry-prometheus
    restart: unless-stopped

volumes:
  grafana-data-volume:
  loki-data-volume:
  prometheus-data-volume:
  pyroscope-data-volume:
  tempo-data-volume:
  alloy-data-volume:
