FROM rust:1.96-bookworm AS builder
RUN apt-get update && apt-get install -y --no-install-recommends protobuf-compiler libprotobuf-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY proto proto
COPY crates/market-feed crates/market-feed
WORKDIR /app/crates/market-feed
RUN --mount=type=cache,target=/usr/local/cargo/registry,sharing=private \
    --mount=type=cache,target=/usr/local/cargo/git,sharing=private \
    --mount=type=cache,target=/app/crates/market-feed/target,sharing=private \
    cargo build --release --bin market-feed \
    && cp /app/crates/market-feed/target/release/market-feed /app/market-feed

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \
    && update-ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/market-feed /app/server
CMD ["/app/server"]
