{
 "title": "Inventory",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(client_inventory_available,client)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "USD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "client_inventory_available{client=~\"$client\", asset=\"USD\"}",
     "legendFormat": "Spendable"
    },
    {
     "expr": "client_inventory_reserved{client=~\"$client\", asset=\"USD\"}",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "BTC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "client_inventory_available{client=~\"$client\", asset=\"BTC\"}",
     "legendFormat": "Spendable"
    },
    {
     "expr": "client_inventory_reserved{client=~\"$client\", asset=\"BTC\"}",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "ETH",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "client_inventory_available{client=~\"$client\", asset=\"ETH\"}",
     "legendFormat": "Spendable"
    },
    {
     "expr": "client_inventory_reserved{client=~\"$client\", asset=\"ETH\"}",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "XMR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "client_inventory_available{client=~\"$client\", asset=\"XMR\"}",
     "legendFormat": "Spendable"
    },
    {
     "expr": "client_inventory_reserved{client=~\"$client\", asset=\"XMR\"}",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "SOL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "client_inventory_available{client=~\"$client\", asset=\"SOL\"}",
     "legendFormat": "Spendable"
    },
    {
     "expr": "client_inventory_reserved{client=~\"$client\", asset=\"SOL\"}",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "XRP",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "client_inventory_available{client=~\"$client\", asset=\"XRP\"}",
     "legendFormat": "Spendable"
    },
    {
     "expr": "client_inventory_reserved{client=~\"$client\", asset=\"XRP\"}",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "Instrument Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "client_subscriptions{client=\"$client\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  }
 ]
}