{
 "title": "Orders",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(client_inventory_available,client)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Open Orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "client_orders_open{client=\"$client\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Submitted Orders: Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(client_orders_submitted_total{client=\"$client\"})",
     "legendFormat": "Submitted"
    }
   ]
  },
  {
   "title": "Submitted Orders: Side",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(side) (client_orders_submitted_total{client=\"$client\"})",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Submitted Orders by Instrument",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instrument) (client_orders_submitted_total{client=\"$client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted BUY Orders by Instrument",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instrument) (client_orders_submitted_total{client=\"$client\", side=\"Buy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted SELL Orders by Instrument",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instrument) (client_orders_submitted_total{client=\"$client\", side=\"Sell\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted Orders Rate by Instrument",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (instrument) (rate(client_orders_submitted_total{client=\"$client\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Submitted Orders Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(client_orders_submitted_total{client=\"$client\"}[$__rate_interval]))",
     "legendFormat": "Submitted"
    }
   ]
  },
  {
   "title": "Submitted Order Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by(side) (rate(client_orders_submitted_total{client=\"$client\"}[$__rate_interval]))",
     "legendFormat": "{{side}}"
    }
   ]
  }
 ]
}