{
 "title": "Trades",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(client_inventory_available,client)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Trade Count: Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(client_trades_total{client=\"$client\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Trade Count: Side",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(side) (client_trades_total{client=\"$client\"})",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Trade Count: Instrument Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instrument) (client_trades_total{client=\"$client\"})",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Trade Count: Instrument Buy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instrument) (client_trades_total{client=\"$client\", side=\"Buy\"})",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Trade Count: Instrument Sell",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instrument) (client_trades_total{client=\"$client\", side=\"Sell\"})",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Trade Quantity: Instrument Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(instrument) (client_trade_quantity_total{client=\"$client\"})",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Trade Quantity: Instrument Buy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum by(instrument) (client_trade_quantity_total{client=\"$client\", side=\"Buy\"})",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Trade Quantity: Instrument Sell",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by(instrument) (client_trade_quantity_total{client=\"$client\", side=\"Sell\"})",
     "legendFormat": "{{side}}"
    }
   ]
  }
 ]
}