[package]
name = "orderbook"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
futures-util = "=0.3.33"
maiya = { git = "https://github.com/Braqzen/maiya.git", tag = "v0.1.0" }
opentelemetry_sdk = "0.32.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros", "signal"] }
tokio-util = "0.7.19"
tokio-tungstenite = "0.30.0"
tracing = "0.1"
