{
 "title": "Asset Price Charts",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BTC-USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "price_generator_price{instrument=\"BTC-USD\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "ETH-USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "price_generator_price{instrument=\"ETH-USD\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "SOL-USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "price_generator_price{instrument=\"SOL-USD\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "XMR-USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "price_generator_price{instrument=\"XMR-USD\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "XRP-USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "price_generator_price{instrument=\"XRP-USD\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  }
 ]
}